#!/bin/bash

# Verifique se o serviço GVM está em execução (é necessário para atualizar)
if ! systemctl is-active gvmd.service >/dev/null 2>&1; then
    echo "O serviço GVM não está em execução. Inicie-o antes de continuar."
    exit 1
fi

# Atualize o NVT (Network Vulnerability Tests) Feed
echo "Atualizando NVT Feed..."
greenbone-nvt-sync

# Atualize o SCAP (Security Content Automation Protocol) Data Feed
echo "Atualizando SCAP Feed..."
greenbone-scapdata-sync

# Atualize o CERT (Cert-Bund) Data
echo "Atualizando CERT Feed..."
greenbone-certdata-sync

# Reinicie o serviço GVM para aplicar as atualizações
echo "Reiniciando o serviço GVM..."
systemctl restart gvmd.service

echo "Atualização concluída!"
